# Generated by Django 5.1.4 on 2024-12-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="theatrehall",
            options={"ordering": ["name"]},
        ),
    ]
