# Generated by Django 5.1.4 on 2024-12-29 16:18

import theatre.path_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_alter_theatrehall_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.path_utils.create_custom_path
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="poster",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre.path_utils.create_custom_path
            ),
        ),
    ]
